
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 0.0.0.0

development:
  <<: *default
  database: milk_round_dev

test:
  <<: *default
  database: milk_round_test


production:
  <<: *default
  database: Jb_portal_production
  username: rails_devise_token_auth
  password: <%= ENV['RAILS_DEVISE_TOKEN_AUTH_DATABASE_PASSWORD'] %>